-- Team 5 [Wadha / Fatma]
-- Physical Schema Structure

--S1
CREATE USER ELECTRIC_VEHICLE1 IDENTIFIED BY student; 

--S2
GRANT RESOURCE TO ELECTRIC_VEHICLE1; 
GRANT UNLIMITED TABLESPACE TO ELECTRIC_VEHICLE1;

--S3
ALTER SESSION SET CURRENT_SCHEMA = ELECTRIC_VEHICLE1;
 
    